# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/exercice4.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(792, 673)
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(10, 0, 771, 661))
        self.frame.setStyleSheet("QFrame{\n"
"    border-radius:13px;\n"
"    background-color:white;\n"
"border:5px solid black;\n"
"text-align: center ;\n"
"\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(120, 40, 75, 23))
        self.pushButton.setStyleSheet("QPushButton{\n"
"    color:black;\n"
"    background-color:white;\n"
"\n"
"    border-radius:none;\n"
"}\n"
"QPushButton:hover{\n"
"    font:bold;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(230, 40, 75, 23))
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"    color:black;\n"
"    background-color:white;\n"
"\n"
"    border-radius:none;\n"
"}\n"
"QPushButton:hover{\n"
"    font:bold;\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame)
        self.pushButton_3.setGeometry(QtCore.QRect(330, 40, 75, 23))
        self.pushButton_3.setStyleSheet("QPushButton{\n"
"    color:black;\n"
"    background-color:white;\n"
"\n"
"    border-radius:none;\n"
"}\n"
"QPushButton:hover{\n"
"    font:bold;\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame)
        self.pushButton_4.setGeometry(QtCore.QRect(430, 40, 75, 23))
        self.pushButton_4.setStyleSheet("QPushButton{\n"
"    color:black;\n"
"    background-color:white;\n"
"\n"
"    border-radius:none;\n"
"}\n"
"QPushButton:hover{\n"
"    font:bold;\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.frame)
        self.pushButton_5.setGeometry(QtCore.QRect(40, 110, 141, 181))
        self.pushButton_5.setStyleSheet("QPushButton{\n"
"    background:#091a57;\n"
"    border-radius:13px;\n"
"    border: 1px solid black;\n"
"}")
        self.pushButton_5.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img4/Static/shortcuts-2018-10-03.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_5.setIcon(icon)
        self.pushButton_5.setIconSize(QtCore.QSize(100, 100))
        self.pushButton_5.setAutoRepeat(False)
        self.pushButton_5.setAutoExclusive(False)
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.frame)
        self.pushButton_6.setGeometry(QtCore.QRect(210, 110, 151, 181))
        self.pushButton_6.setStyleSheet("QPushButton{\n"
"    background:#e31079;\n"
"    border-radius:13px;\n"
"    border: 1px solid black;\n"
"}")
        self.pushButton_6.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/img4/Static/ojo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_6.setIcon(icon1)
        self.pushButton_6.setIconSize(QtCore.QSize(100, 100))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.frame)
        self.pushButton_7.setGeometry(QtCore.QRect(400, 110, 141, 181))
        self.pushButton_7.setStyleSheet("QPushButton{\n"
"    background:#ccfcff;\n"
"    border-radius:13px;\n"
"    border: 1px solid black;\n"
"}")
        self.pushButton_7.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/img4/Static/fnJon5rf-removebg-preview.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_7.setIcon(icon2)
        self.pushButton_7.setIconSize(QtCore.QSize(120, 120))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.frame)
        self.pushButton_8.setGeometry(QtCore.QRect(590, 110, 141, 181))
        self.pushButton_8.setStyleSheet("QPushButton{\n"
"    background:#b1f2d2;\n"
"    border-radius:13px;\n"
"    border: 1px solid black;\n"
"}")
        self.pushButton_8.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/img4/Static/833453.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_8.setIcon(icon3)
        self.pushButton_8.setIconSize(QtCore.QSize(100, 100))
        self.pushButton_8.setObjectName("pushButton_8")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(360, 440, 321, 171))
        self.frame_2.setStyleSheet("QFrame{\n"
"\n"
"background-color:white;\n"
"border:1px solid }")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.pushButton_12 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_12.setGeometry(QtCore.QRect(10, 10, 61, 71))
        self.pushButton_12.setStyleSheet("QPushButton{\n"
"    background-color:#6279b5;\n"
"    border:1px solid black;\n"
"    border-raduis:13px;\n"
"}")
        self.pushButton_12.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/img4/Static/thumb2-blue-abstract-waves-creative-blue-wavy-background-blue-backgrounds-abstract-waves-removebg-preview.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_12.setIcon(icon4)
        self.pushButton_12.setIconSize(QtCore.QSize(60, 70))
        self.pushButton_12.setObjectName("pushButton_12")
        self.label_9 = QtWidgets.QLabel(self.frame_2)
        self.label_9.setGeometry(QtCore.QRect(80, 10, 211, 71))
        self.label_9.setStyleSheet("QLabel{\n"
"    border:1px solid white;\n"
"\n"
"}")
        self.label_9.setObjectName("label_9")
        self.pushButton_13 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_13.setGeometry(QtCore.QRect(90, 130, 51, 26))
        self.pushButton_13.setStyleSheet("QPushButton{\n"
"    background-color:white;\n"
"    border:none;\n"
"}")
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_14 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_14.setGeometry(QtCore.QRect(260, 130, 51, 26))
        self.pushButton_14.setStyleSheet("QPushButton{\n"
"    background-color:white;\n"
"    border:none;\n"
"}")
        self.pushButton_14.setObjectName("pushButton_14")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(30, 310, 91, 21))
        self.label.setStyleSheet("QLabel{\n"
"    border:none;\n"
"}")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(190, 310, 101, 21))
        self.label_2.setStyleSheet("QLabel{\n"
"    border:none;\n"
"}")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(350, 310, 91, 21))
        self.label_3.setStyleSheet("QLabel{\n"
"    border:none;\n"
"}")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(500, 300, 81, 21))
        self.label_4.setStyleSheet("QLabel{\n"
"    border:none;\n"
"}")
        self.label_4.setObjectName("label_4")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(110, 530, 161, 71))
        self.label_6.setStyleSheet("QFrame{\n"
"border:1px solid white;\n"
"}")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(30, 390, 61, 31))
        self.label_7.setStyleSheet("QLabel{\n"
"    border:none;\n"
"}\n"
"")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(360, 380, 101, 41))
        self.label_8.setStyleSheet("QLabel{\n"
"    border:none;\n"
"}\n"
"")
        self.label_8.setObjectName("label_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.frame)
        self.pushButton_9.setGeometry(QtCore.QRect(30, 20, 61, 51))
        self.pushButton_9.setStyleSheet("QPushButton{\n"
"    color:black;\n"
"    background-color:white;\n"
"\n"
"    border-radius:none;\n"
"}")
        self.pushButton_9.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/img4/Static/117-1172644_category-comments-four-square-icon-png-clipart-removebg-preview.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_9.setIcon(icon5)
        self.pushButton_9.setIconSize(QtCore.QSize(60, 50))
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(self.frame)
        self.pushButton_10.setGeometry(QtCore.QRect(30, 440, 71, 71))
        self.pushButton_10.setStyleSheet("\n"
"QPushButton{\n"
"    background-color:#6279b5;\n"
"    border:1px solid black;\n"
"    border-raduis:12px;\n"
"}")
        self.pushButton_10.setText("")
        self.pushButton_10.setIcon(icon4)
        self.pushButton_10.setIconSize(QtCore.QSize(69, 69))
        self.pushButton_10.setCheckable(True)
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(self.frame)
        self.pushButton_11.setGeometry(QtCore.QRect(30, 530, 71, 71))
        self.pushButton_11.setStyleSheet("QPushButton{\n"
"    background-color:#6279b5;\n"
"    border:1px solid black;\n"
"    border-raduis:12px;\n"
"}")
        self.pushButton_11.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/img4/Static/110254-orange-wave-free-download-png-hd.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_11.setIcon(icon6)
        self.pushButton_11.setIconSize(QtCore.QSize(67, 70))
        self.pushButton_11.setObjectName("pushButton_11")
        self.label_10 = QtWidgets.QLabel(self.frame)
        self.label_10.setGeometry(QtCore.QRect(110, 440, 211, 71))
        self.label_10.setStyleSheet("QLabel{\n"
"    border:1px solid white;\n"
"\n"
"}")
        self.label_10.setObjectName("label_10")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton.setText(_translate("Dialog", "Home"))
        self.pushButton_2.setText(_translate("Dialog", "Popular"))
        self.pushButton_3.setText(_translate("Dialog", "Search"))
        self.pushButton_4.setText(_translate("Dialog", "Podcosters"))
        self.label_9.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Why Many WEbsites</span></p><p><span style=\" font-size:14pt; font-weight:600;\">Do Not Survive.</span></p><p><span style=\" font-size:10pt;\">Outcharge -36min</span></p></body></html>"))
        self.pushButton_13.setText(_translate("Dialog", "12:42"))
        self.pushButton_14.setText(_translate("Dialog", "-23:18"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Design</span></p></body></html>"))
        self.label_2.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Livestyle</span></p></body></html>"))
        self.label_3.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Productivity</span></p></body></html>"))
        self.label_4.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Motivation</span></p></body></html>"))
        self.label_6.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Brandinf For Business.</span></p><p><span style=\" font-size:14pt; font-weight:600;\">How To Make Your.</span></p><p><span style=\" font-size:11pt;\">Outcharge -35min</span></p></body></html>"))
        self.label_7.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Trends</span></p></body></html>"))
        self.label_8.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Now playing</span></p></body></html>"))
        self.label_10.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Why Many WEbsites</span></p><p><span style=\" font-size:14pt; font-weight:600;\">Do Not Survive.</span></p><p><span style=\" font-size:10pt;\">Outcharge -36min</span></p></body></html>"))
import ressources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
