# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/exercice3.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(950, 620)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 9, 941, 581))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(10, 0, 951, 591))
        self.label.setStyleSheet("border-radius:25px;color:white;\n"
"image: url(:/images/Static/screen.png);")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/images/Static/screen.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(500, 20, 421, 541))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.frame_2.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.frame_2.setFont(font)
        self.frame_2.setStyleSheet("background-color:black;border-radius:12px;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_2.setObjectName("frame_2")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(160, 30, 60, 16))
        self.label_2.setStyleSheet("QLabel{\n"
"    color: rgb(133,133,133);\n"
"    \n"
"}\n"
"QLabel:hover{\n"
"    color: white;\n"
"    font:bold;\n"
"    \n"
"}")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setGeometry(QtCore.QRect(240, 30, 60, 16))
        self.label_3.setStyleSheet("QLabel{\n"
"    color: rgb(133,133,133);\n"
"    \n"
"}\n"
"QLabel:hover{\n"
"    color: white;\n"
"    font:bold;\n"
"    \n"
"}")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setGeometry(QtCore.QRect(320, 30, 71, 20))
        self.label_4.setStyleSheet("QLabel{\n"
"    color: rgb(133,133,133);\n"
"    \n"
"}\n"
"QLabel:hover{\n"
"    color: white;\n"
"    font:bold;\n"
"    \n"
"}")
        self.label_4.setObjectName("label_4")
        self.pushButton = QtWidgets.QPushButton(self.frame_2)
        self.pushButton.setGeometry(QtCore.QRect(60, 100, 101, 26))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton {\n"
"color:rgb(133,133,133);\n"
"font-size:13px;\n"
"border-width:10px;\n"
"border-radius:none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"color:white;\n"
"border: 1px solid white;\n"
"font: bold;\n"
"\n"
"}")
        self.pushButton.setCheckable(False)
        self.pushButton.setAutoDefault(False)
        self.pushButton.setDefault(False)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_2.setGeometry(QtCore.QRect(180, 100, 81, 26))
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"color:rgb(133,133,133);\n"
"font-size:13px;\n"
"border-width:10px;\n"
"border-radius:none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"color:white;\n"
"border: 1px solid white;\n"
"font: bold;\n"
"\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_3.setGeometry(QtCore.QRect(280, 100, 81, 26))
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"color:rgb(133,133,133);\n"
"font-size:13px;\n"
"border-width:10px;\n"
"border-radius:none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"color:white;\n"
"border: 1px solid white;\n"
"font: bold;\n"
"\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_4.setGeometry(QtCore.QRect(60, 140, 111, 26))
        self.pushButton_4.setStyleSheet("QPushButton {\n"
"color:rgb(133,133,133);\n"
"font-size:13px;\n"
"border-width:10px;\n"
"border-radius:none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"color:white;\n"
"border: 1px solid white;\n"
"font: bold;\n"
"\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_5.setGeometry(QtCore.QRect(190, 140, 81, 26))
        self.pushButton_5.setStyleSheet("QPushButton {\n"
"color:rgb(133,133,133);\n"
"font-size:13px;\n"
"border-width:10px;\n"
"border-radius:none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"color:white;\n"
"border: 1px solid white;\n"
"font: bold;\n"
"\n"
"}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.lineEdit = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit.setGeometry(QtCore.QRect(60, 210, 311, 31))
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.lineEdit.setFont(font)
        self.lineEdit.setMouseTracking(True)
        self.lineEdit.setAcceptDrops(True)
        self.lineEdit.setAutoFillBackground(False)
        self.lineEdit.setStyleSheet("QLineEdit{\n"
"    color:rgb(133,133,133);\n"
"    border-radius:none;\n"
"    border-bottom:1px solid rgb(133,133,133);\n"
"}\n"
"QLineEdit:hover{\n"
"    color:white;\n"
"    font:bold;\n"
"    border-bottom:2px solid white;\n"
"}")
        self.lineEdit.setText("")
        self.lineEdit.setClearButtonEnabled(True)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_2.setGeometry(QtCore.QRect(60, 270, 321, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_2.setStyleSheet("QLineEdit{\n"
"    color:rgb(133,133,133);\n"
"    border-radius:none;\n"
"    border-bottom:1px solid rgb(133,133,133);\n"
"}\n"
"QLineEdit:hover{\n"
"    color:white;\n"
"    font:bold;\n"
"    border-bottom:2px solid white;\n"
"}")
        self.lineEdit_2.setClearButtonEnabled(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_3.setGeometry(QtCore.QRect(60, 330, 311, 31))
        self.lineEdit_3.setStyleSheet("QLineEdit{\n"
"    color:rgb(133,133,133);\n"
"    border-radius:none;\n"
"    border-bottom:1px solid rgb(133,133,133);\n"
"}\n"
"QLineEdit:hover{\n"
"    color:white;\n"
"    font:bold;\n"
"    border-bottom:2px solid white;\n"
"}")
        self.lineEdit_3.setClearButtonEnabled(True)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.commandLinkButton = QtWidgets.QCommandLinkButton(self.frame_2)
        self.commandLinkButton.setGeometry(QtCore.QRect(60, 420, 168, 41))
        self.commandLinkButton.setStyleSheet("color:white;\n"
"font-size:13px;\n"
"")
        self.commandLinkButton.setObjectName("commandLinkButton")
        self.pushButton_6 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_6.setGeometry(QtCore.QRect(60, 480, 141, 26))
        self.pushButton_6.setStyleSheet("QPushButton{\n"
"background-color:white;\n"
"    color:black;\n"
"    border-radius:none;\n"
"    font:Arial 12px bold ;\n"
"    \n"
"}")
        self.pushButton_6.setObjectName("pushButton_6")
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setGeometry(QtCore.QRect(60, 70, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color:white;")
        self.label_5.setObjectName("label_5")
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.pushButton.raise_()
        self.pushButton_2.raise_()
        self.pushButton_3.raise_()
        self.pushButton_5.raise_()
        self.lineEdit.raise_()
        self.lineEdit_2.raise_()
        self.lineEdit_3.raise_()
        self.commandLinkButton.raise_()
        self.pushButton_6.raise_()
        self.pushButton_4.raise_()
        self.label_5.raise_()
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(90, 160, 311, 191))
        self.label_6.setStyleSheet("QLabel{\n"
"    color:white;\n"
"}")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(89, 40, 151, 41))
        self.label_7.setStyleSheet("QLabel{\n"
"    color:white;\n"
"}")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(90, 490, 251, 31))
        self.label_8.setStyleSheet("QLabel{\n"
"    color:white;\n"
"}")
        self.label_8.setObjectName("label_8")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Work</p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">About</p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Contacts</p></body></html>"))
        self.pushButton.setText(_translate("MainWindow", "UI/UX design"))
        self.pushButton_2.setText(_translate("MainWindow", "Website"))
        self.pushButton_3.setText(_translate("MainWindow", "Branding"))
        self.pushButton_4.setText(_translate("MainWindow", "Design system"))
        self.pushButton_5.setText(_translate("MainWindow", "Other"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "your name"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "Your email"))
        self.lineEdit_3.setPlaceholderText(_translate("MainWindow", "Tell us about your projet"))
        self.commandLinkButton.setText(_translate("MainWindow", "Add  attachment"))
        self.pushButton_6.setText(_translate("MainWindow", "Sent request"))
        self.label_5.setText(_translate("MainWindow", "I\'m interested in..."))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:36pt; font-weight:600;\">Have a project?</span></p><p><span style=\" font-size:36pt; font-weight:600;\">We would love </span></p><p><span style=\" font-size:36pt; font-weight:600;\">to help.</span></p></body></html>"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">ZERO GRAVITE</span></p></body></html>"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">zerogravitydsgn@gmail.com</span></p></body></html>"))
import resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
