# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/fichier.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Nan(object):
    def setupUi(self, Nan):
        Nan.setObjectName("Nan")
        Nan.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(Nan)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-20, -10, 821, 571))
        self.label.setStyleSheet("background-image: url(:/images/Static/screen.png);")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/images/Static/screen.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(130, 70, 291, 151))
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(490, 340, 111, 61))
        self.pushButton.setObjectName("pushButton")
        self.btn = QtWidgets.QPushButton(self.centralwidget)
        self.btn.setGeometry(QtCore.QRect(440, 140, 81, 26))
        self.btn.setObjectName("btn")
        Nan.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Nan)
        self.statusbar.setObjectName("statusbar")
        Nan.setStatusBar(self.statusbar)

        self.retranslateUi(Nan)
        QtCore.QMetaObject.connectSlotsByName(Nan)

    def retranslateUi(self, Nan):
        _translate = QtCore.QCoreApplication.translate
        Nan.setWindowTitle(_translate("Nan", "MainWindow"))
        self.label_2.setText(_translate("Nan", "<html><head/><body><p><span style=\" font-size:24pt;\">HELLO WORLD</span></p></body></html>"))
        self.pushButton.setText(_translate("Nan", "PushButton"))
        self.btn.setText(_translate("Nan", "PushButton"))
import ressource_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Nan = QtWidgets.QMainWindow()
    ui = Ui_Nan()
    ui.setupUi(Nan)
    Nan.show()
    sys.exit(app.exec_())
